apiVersion: networking.k8s.io/v1
kind: Ingress                # Ingress is the "front door" of your cluster.
                             # It receives all external traffic and routes it
                             # to the right Service based on the URL path.
                             # Without Ingress you'd need a separate LoadBalancer
                             # per service which gets expensive on AWS.
metadata:
  name: talentflow-ingress
spec:
  # ingressClassName is the modern way to specify which ingress controller to use.
  # On AWS EKS you'd change this to "alb" to use the AWS Load Balancer Controller.
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Any request to /api/* goes to the backend service.
          # e.g. yourapp.com/api/jobs → backend-service:80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80

          # Everything else goes to the frontend service.
          # e.g. yourapp.com/ → frontend-service:80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
